name: develop-formatters

on:
  push:
    branches:
      - main
    paths:
      - 'formatters/**'
  pull_request:
    paths:
      - 'formatters/**'

jobs:
  check:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./formatters
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v26
        with:
          extra_nix_config: 'experimental-features = nix-command flakes'
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main

      - name: Install packages
        run: nix develop
